
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const BuyMAccordionContent: typeof import("../components/buy/mAccordion/Content.vue")['default']
export const BuyMAnchor: typeof import("../components/buy/mAnchor.vue")['default']
export const BuyMAutoComplete: typeof import("../components/buy/mAutoComplete.vue")['default']
export const BuyMDialog: typeof import("../components/buy/mDialog.vue")['default']
export const BuyMErrorMessageElem: typeof import("../components/buy/mErrorMessageElem.vue")['default']
export const BuyMFormCheckBox: typeof import("../components/buy/mForm/CheckBox.vue")['default']
export const BuyMFormInput: typeof import("../components/buy/mForm/Input.vue")['default']
export const BuyMFormLabel: typeof import("../components/buy/mForm/Label.vue")['default']
export const BuyMFormRadio: typeof import("../components/buy/mForm/Radio.vue")['default']
export const BuyMFormRadiosOval: typeof import("../components/buy/mForm/RadiosOval.vue")['default']
export const BuyMFormSelect: typeof import("../components/buy/mForm/Select.vue")['default']
export const BuyMFormSelectDropdown: typeof import("../components/buy/mForm/SelectDropdown.vue")['default']
export const BuyMItemContainer: typeof import("../components/buy/mItem/Container.vue")['default']
export const BuyMItemMain: typeof import("../components/buy/mItem/Main.vue")['default']
export const BuyMItemSwitchItem: typeof import("../components/buy/mItem/SwitchItem.vue")['default']
export const BuyMPagination: typeof import("../components/buy/mPagination.vue")['default']
export const BuyMPopup: typeof import("../components/buy/mPopup.vue")['default']
export const BuyMSeparator: typeof import("../components/buy/mSeparator.vue")['default']
export const BuyMSortMain: typeof import("../components/buy/mSort/Main.vue")['default']
export const BuyMSwiper12: typeof import("../components/buy/mSwiper12.vue")['default']
export const BuyMTabCheck: typeof import("../components/buy/mTab/Check.vue")['default']
export const BuyMTabOvalResponsiv: typeof import("../components/buy/mTab/OvalResponsiv.vue")['default']
export const BuyMTabSeparator: typeof import("../components/buy/mTab/Separator.vue")['default']
export const BuyMTagCheckBox: typeof import("../components/buy/mTag/CheckBox.vue")['default']
export const BuyMTagDefault: typeof import("../components/buy/mTag/Default.vue")['default']
export const BuyMTitleBorderBottom: typeof import("../components/buy/mTitle/BorderBottom.vue")['default']
export const CommonImgSrc: typeof import("../components/common/ImgSrc.vue")['default']
export const CommonSvgIcon: typeof import("../components/common/SvgIcon.vue")['default']
export const CommonMContainer: typeof import("../components/common/mContainer.vue")['default']
export const CommonMContent: typeof import("../components/common/mContent.vue")['default']
export const CommonMFooter: typeof import("../components/common/mFooter.vue")['default']
export const CommonMHeader: typeof import("../components/common/mHeader.vue")['default']
export const CommonMLoading: typeof import("../components/common/mLoading.vue")['default']
export const CommonMNav: typeof import("../components/common/mNav.vue")['default']
export const BuyCustomPopup: typeof import("../containers/buy/CustomPopup.vue")['default']
export const CommonAlertSystem: typeof import("../containers/common/AlertSystem.vue")['default']
export const CommonConfirmSystem: typeof import("../containers/common/ConfirmSystem.vue")['default']
export const PageBuyListContent: typeof import("../pages/buy/_components/List/Content.vue")['default']
export const PageBuyListSearchFilter: typeof import("../pages/buy/_components/List/SearchFilter.vue")['default']
export const PageBuyListSearchFunction: typeof import("../pages/buy/_components/List/SearchFunction.vue")['default']
export const PageBuyListTabOvalResponsiv: typeof import("../pages/buy/_components/List/TabOvalResponsiv.vue")['default']
export const PageBuyListContentItem: typeof import("../pages/buy/_components/List/content/Item.vue")['default']
export const PageBuyListContentMediaImages: typeof import("../pages/buy/_components/List/content/MediaImages.vue")['default']
export const PageBuyListSearchCategory: typeof import("../pages/buy/_components/List/search/Category.vue")['default']
export const PageBuyListSearchCondition: typeof import("../pages/buy/_components/List/search/Condition.vue")['default']
export const PageBuyListSearchKeyword: typeof import("../pages/buy/_components/List/search/Keyword.vue")['default']
export const PageBuyListSearchMaxMinRange: typeof import("../pages/buy/_components/List/search/MaxMinRange.vue")['default']
export const PageBuyListSearchMore: typeof import("../pages/buy/_components/List/search/More.vue")['default']
export const PageBuyListSearchMrt: typeof import("../pages/buy/_components/List/search/Mrt.vue")['default']
export const PageBuyListSearchPrice: typeof import("../pages/buy/_components/List/search/Price.vue")['default']
export const PageBuyListSearchPurpose: typeof import("../pages/buy/_components/List/search/Purpose.vue")['default']
export const PageBuyListSearchRegion: typeof import("../pages/buy/_components/List/search/Region.vue")['default']
export const PageBuyListSearchRoom: typeof import("../pages/buy/_components/List/search/Room.vue")['default']
export const PageBuyListSearchSort: typeof import("../pages/buy/_components/List/search/Sort.vue")['default']
export const PageBuyListSearchMoreAge: typeof import("../pages/buy/_components/List/search/more/Age.vue")['default']
export const PageBuyListSearchMoreFace: typeof import("../pages/buy/_components/List/search/more/Face.vue")['default']
export const PageBuyListSearchMoreFloor: typeof import("../pages/buy/_components/List/search/more/Floor.vue")['default']
export const PageBuyListSearchMoreNearBy: typeof import("../pages/buy/_components/List/search/more/NearBy.vue")['default']
export const PageBuyListSearchMoreParkingMode: typeof import("../pages/buy/_components/List/search/more/ParkingMode.vue")['default']
export const PageBuyListSearchMorePin: typeof import("../pages/buy/_components/List/search/more/Pin.vue")['default']
export const PageBuyListSearchMoreType: typeof import("../pages/buy/_components/List/search/more/Type.vue")['default']
export const PageBuyListSearchMoreUnitPrice: typeof import("../pages/buy/_components/List/search/more/UnitPrice.vue")['default']
export const PageBuyListSearchPriceRepayment: typeof import("../pages/buy/_components/List/search/price/Repayment.vue")['default']
export const PageBuyListSearchPriceTotal: typeof import("../pages/buy/_components/List/search/price/Total.vue")['default']
export const PageBuyHouseActualPrice: typeof import("../pages/buy/_components/house/ActualPrice.vue")['default']
export const PageBuyHouseBasic: typeof import("../pages/buy/_components/house/Basic.vue")['default']
export const PageBuyHouseBreadcrumbs: typeof import("../pages/buy/_components/house/Breadcrumbs.vue")['default']
export const PageBuyHouseCommunity: typeof import("../pages/buy/_components/house/Community.vue")['default']
export const PageBuyHouseConstruction: typeof import("../pages/buy/_components/house/Construction.vue")['default']
export const PageBuyHouseEnvironment: typeof import("../pages/buy/_components/house/Environment.vue")['default']
export const PageBuyHouseFeatures: typeof import("../pages/buy/_components/house/Features.vue")['default']
export const PageBuyHouseFocus: typeof import("../pages/buy/_components/house/Focus.vue")['default']
export const PageBuyHouseInformation: typeof import("../pages/buy/_components/house/Information.vue")['default']
export const PageBuyHousePopupAskMessage: typeof import("../pages/buy/_components/house/PopupAskMessage.vue")['default']
export const PageBuyHouseRecommend: typeof import("../pages/buy/_components/house/Recommend.vue")['default']
export const PageBuyHouseSelections: typeof import("../pages/buy/_components/house/Selections.vue")['default']
export const PageBuyHouseSocialLife: typeof import("../pages/buy/_components/house/SocialLife.vue")['default']
export const PageBuyHouseContent: typeof import("../pages/buy/_components/house/_Content.vue")['default']
export const PageBuyHouseLabel: typeof import("../pages/buy/_components/house/_Label.vue")['default']
export const PageBuyHouseBasicAccountInfo: typeof import("../pages/buy/_components/house/basic/AccountInfo.vue")['default']
export const PageBuyHouseBasicAddressInfo: typeof import("../pages/buy/_components/house/basic/AddressInfo.vue")['default']
export const PageBuyHouseBasicHouseInfo: typeof import("../pages/buy/_components/house/basic/HouseInfo.vue")['default']
export const PageBuyHouseBasicLayoutInfo: typeof import("../pages/buy/_components/house/basic/LayoutInfo.vue")['default']
export const PageBuyHouseBasicMedia: typeof import("../pages/buy/_components/house/basic/Media.vue")['default']
export const PageBuyHouseBasicMediaImages: typeof import("../pages/buy/_components/house/basic/MediaImages.vue")['default']
export const PageBuyHouseBasicPriceInfo: typeof import("../pages/buy/_components/house/basic/PriceInfo.vue")['default']
export const PageBuyHouseInformationBasic: typeof import("../pages/buy/_components/house/information/Basic.vue")['default']
export const PageBuyHouseInformationFunction: typeof import("../pages/buy/_components/house/information/Function.vue")['default']
export const PageBuyHouseInformationOther: typeof import("../pages/buy/_components/house/information/Other.vue")['default']
export const PageBuyHouseInformationParking: typeof import("../pages/buy/_components/house/information/Parking.vue")['default']
export const PageBuyHouseInformationPin: typeof import("../pages/buy/_components/house/information/Pin.vue")['default']
export const PageBuyHouseInformationPrice: typeof import("../pages/buy/_components/house/information/Price.vue")['default']
export const PageBuyHouseInformationContainer: typeof import("../pages/buy/_components/house/information/_Container.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const Field: typeof import("vee-validate")['Field']
export const FieldArray: typeof import("vee-validate")['FieldArray']
export const Form: typeof import("vee-validate")['Form']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyBuyMAccordionContent: LazyComponent<typeof import("../components/buy/mAccordion/Content.vue")['default']>
export const LazyBuyMAnchor: LazyComponent<typeof import("../components/buy/mAnchor.vue")['default']>
export const LazyBuyMAutoComplete: LazyComponent<typeof import("../components/buy/mAutoComplete.vue")['default']>
export const LazyBuyMDialog: LazyComponent<typeof import("../components/buy/mDialog.vue")['default']>
export const LazyBuyMErrorMessageElem: LazyComponent<typeof import("../components/buy/mErrorMessageElem.vue")['default']>
export const LazyBuyMFormCheckBox: LazyComponent<typeof import("../components/buy/mForm/CheckBox.vue")['default']>
export const LazyBuyMFormInput: LazyComponent<typeof import("../components/buy/mForm/Input.vue")['default']>
export const LazyBuyMFormLabel: LazyComponent<typeof import("../components/buy/mForm/Label.vue")['default']>
export const LazyBuyMFormRadio: LazyComponent<typeof import("../components/buy/mForm/Radio.vue")['default']>
export const LazyBuyMFormRadiosOval: LazyComponent<typeof import("../components/buy/mForm/RadiosOval.vue")['default']>
export const LazyBuyMFormSelect: LazyComponent<typeof import("../components/buy/mForm/Select.vue")['default']>
export const LazyBuyMFormSelectDropdown: LazyComponent<typeof import("../components/buy/mForm/SelectDropdown.vue")['default']>
export const LazyBuyMItemContainer: LazyComponent<typeof import("../components/buy/mItem/Container.vue")['default']>
export const LazyBuyMItemMain: LazyComponent<typeof import("../components/buy/mItem/Main.vue")['default']>
export const LazyBuyMItemSwitchItem: LazyComponent<typeof import("../components/buy/mItem/SwitchItem.vue")['default']>
export const LazyBuyMPagination: LazyComponent<typeof import("../components/buy/mPagination.vue")['default']>
export const LazyBuyMPopup: LazyComponent<typeof import("../components/buy/mPopup.vue")['default']>
export const LazyBuyMSeparator: LazyComponent<typeof import("../components/buy/mSeparator.vue")['default']>
export const LazyBuyMSortMain: LazyComponent<typeof import("../components/buy/mSort/Main.vue")['default']>
export const LazyBuyMSwiper12: LazyComponent<typeof import("../components/buy/mSwiper12.vue")['default']>
export const LazyBuyMTabCheck: LazyComponent<typeof import("../components/buy/mTab/Check.vue")['default']>
export const LazyBuyMTabOvalResponsiv: LazyComponent<typeof import("../components/buy/mTab/OvalResponsiv.vue")['default']>
export const LazyBuyMTabSeparator: LazyComponent<typeof import("../components/buy/mTab/Separator.vue")['default']>
export const LazyBuyMTagCheckBox: LazyComponent<typeof import("../components/buy/mTag/CheckBox.vue")['default']>
export const LazyBuyMTagDefault: LazyComponent<typeof import("../components/buy/mTag/Default.vue")['default']>
export const LazyBuyMTitleBorderBottom: LazyComponent<typeof import("../components/buy/mTitle/BorderBottom.vue")['default']>
export const LazyCommonImgSrc: LazyComponent<typeof import("../components/common/ImgSrc.vue")['default']>
export const LazyCommonSvgIcon: LazyComponent<typeof import("../components/common/SvgIcon.vue")['default']>
export const LazyCommonMContainer: LazyComponent<typeof import("../components/common/mContainer.vue")['default']>
export const LazyCommonMContent: LazyComponent<typeof import("../components/common/mContent.vue")['default']>
export const LazyCommonMFooter: LazyComponent<typeof import("../components/common/mFooter.vue")['default']>
export const LazyCommonMHeader: LazyComponent<typeof import("../components/common/mHeader.vue")['default']>
export const LazyCommonMLoading: LazyComponent<typeof import("../components/common/mLoading.vue")['default']>
export const LazyCommonMNav: LazyComponent<typeof import("../components/common/mNav.vue")['default']>
export const LazyBuyCustomPopup: LazyComponent<typeof import("../containers/buy/CustomPopup.vue")['default']>
export const LazyCommonAlertSystem: LazyComponent<typeof import("../containers/common/AlertSystem.vue")['default']>
export const LazyCommonConfirmSystem: LazyComponent<typeof import("../containers/common/ConfirmSystem.vue")['default']>
export const LazyPageBuyListContent: LazyComponent<typeof import("../pages/buy/_components/List/Content.vue")['default']>
export const LazyPageBuyListSearchFilter: LazyComponent<typeof import("../pages/buy/_components/List/SearchFilter.vue")['default']>
export const LazyPageBuyListSearchFunction: LazyComponent<typeof import("../pages/buy/_components/List/SearchFunction.vue")['default']>
export const LazyPageBuyListTabOvalResponsiv: LazyComponent<typeof import("../pages/buy/_components/List/TabOvalResponsiv.vue")['default']>
export const LazyPageBuyListContentItem: LazyComponent<typeof import("../pages/buy/_components/List/content/Item.vue")['default']>
export const LazyPageBuyListContentMediaImages: LazyComponent<typeof import("../pages/buy/_components/List/content/MediaImages.vue")['default']>
export const LazyPageBuyListSearchCategory: LazyComponent<typeof import("../pages/buy/_components/List/search/Category.vue")['default']>
export const LazyPageBuyListSearchCondition: LazyComponent<typeof import("../pages/buy/_components/List/search/Condition.vue")['default']>
export const LazyPageBuyListSearchKeyword: LazyComponent<typeof import("../pages/buy/_components/List/search/Keyword.vue")['default']>
export const LazyPageBuyListSearchMaxMinRange: LazyComponent<typeof import("../pages/buy/_components/List/search/MaxMinRange.vue")['default']>
export const LazyPageBuyListSearchMore: LazyComponent<typeof import("../pages/buy/_components/List/search/More.vue")['default']>
export const LazyPageBuyListSearchMrt: LazyComponent<typeof import("../pages/buy/_components/List/search/Mrt.vue")['default']>
export const LazyPageBuyListSearchPrice: LazyComponent<typeof import("../pages/buy/_components/List/search/Price.vue")['default']>
export const LazyPageBuyListSearchPurpose: LazyComponent<typeof import("../pages/buy/_components/List/search/Purpose.vue")['default']>
export const LazyPageBuyListSearchRegion: LazyComponent<typeof import("../pages/buy/_components/List/search/Region.vue")['default']>
export const LazyPageBuyListSearchRoom: LazyComponent<typeof import("../pages/buy/_components/List/search/Room.vue")['default']>
export const LazyPageBuyListSearchSort: LazyComponent<typeof import("../pages/buy/_components/List/search/Sort.vue")['default']>
export const LazyPageBuyListSearchMoreAge: LazyComponent<typeof import("../pages/buy/_components/List/search/more/Age.vue")['default']>
export const LazyPageBuyListSearchMoreFace: LazyComponent<typeof import("../pages/buy/_components/List/search/more/Face.vue")['default']>
export const LazyPageBuyListSearchMoreFloor: LazyComponent<typeof import("../pages/buy/_components/List/search/more/Floor.vue")['default']>
export const LazyPageBuyListSearchMoreNearBy: LazyComponent<typeof import("../pages/buy/_components/List/search/more/NearBy.vue")['default']>
export const LazyPageBuyListSearchMoreParkingMode: LazyComponent<typeof import("../pages/buy/_components/List/search/more/ParkingMode.vue")['default']>
export const LazyPageBuyListSearchMorePin: LazyComponent<typeof import("../pages/buy/_components/List/search/more/Pin.vue")['default']>
export const LazyPageBuyListSearchMoreType: LazyComponent<typeof import("../pages/buy/_components/List/search/more/Type.vue")['default']>
export const LazyPageBuyListSearchMoreUnitPrice: LazyComponent<typeof import("../pages/buy/_components/List/search/more/UnitPrice.vue")['default']>
export const LazyPageBuyListSearchPriceRepayment: LazyComponent<typeof import("../pages/buy/_components/List/search/price/Repayment.vue")['default']>
export const LazyPageBuyListSearchPriceTotal: LazyComponent<typeof import("../pages/buy/_components/List/search/price/Total.vue")['default']>
export const LazyPageBuyHouseActualPrice: LazyComponent<typeof import("../pages/buy/_components/house/ActualPrice.vue")['default']>
export const LazyPageBuyHouseBasic: LazyComponent<typeof import("../pages/buy/_components/house/Basic.vue")['default']>
export const LazyPageBuyHouseBreadcrumbs: LazyComponent<typeof import("../pages/buy/_components/house/Breadcrumbs.vue")['default']>
export const LazyPageBuyHouseCommunity: LazyComponent<typeof import("../pages/buy/_components/house/Community.vue")['default']>
export const LazyPageBuyHouseConstruction: LazyComponent<typeof import("../pages/buy/_components/house/Construction.vue")['default']>
export const LazyPageBuyHouseEnvironment: LazyComponent<typeof import("../pages/buy/_components/house/Environment.vue")['default']>
export const LazyPageBuyHouseFeatures: LazyComponent<typeof import("../pages/buy/_components/house/Features.vue")['default']>
export const LazyPageBuyHouseFocus: LazyComponent<typeof import("../pages/buy/_components/house/Focus.vue")['default']>
export const LazyPageBuyHouseInformation: LazyComponent<typeof import("../pages/buy/_components/house/Information.vue")['default']>
export const LazyPageBuyHousePopupAskMessage: LazyComponent<typeof import("../pages/buy/_components/house/PopupAskMessage.vue")['default']>
export const LazyPageBuyHouseRecommend: LazyComponent<typeof import("../pages/buy/_components/house/Recommend.vue")['default']>
export const LazyPageBuyHouseSelections: LazyComponent<typeof import("../pages/buy/_components/house/Selections.vue")['default']>
export const LazyPageBuyHouseSocialLife: LazyComponent<typeof import("../pages/buy/_components/house/SocialLife.vue")['default']>
export const LazyPageBuyHouseContent: LazyComponent<typeof import("../pages/buy/_components/house/_Content.vue")['default']>
export const LazyPageBuyHouseLabel: LazyComponent<typeof import("../pages/buy/_components/house/_Label.vue")['default']>
export const LazyPageBuyHouseBasicAccountInfo: LazyComponent<typeof import("../pages/buy/_components/house/basic/AccountInfo.vue")['default']>
export const LazyPageBuyHouseBasicAddressInfo: LazyComponent<typeof import("../pages/buy/_components/house/basic/AddressInfo.vue")['default']>
export const LazyPageBuyHouseBasicHouseInfo: LazyComponent<typeof import("../pages/buy/_components/house/basic/HouseInfo.vue")['default']>
export const LazyPageBuyHouseBasicLayoutInfo: LazyComponent<typeof import("../pages/buy/_components/house/basic/LayoutInfo.vue")['default']>
export const LazyPageBuyHouseBasicMedia: LazyComponent<typeof import("../pages/buy/_components/house/basic/Media.vue")['default']>
export const LazyPageBuyHouseBasicMediaImages: LazyComponent<typeof import("../pages/buy/_components/house/basic/MediaImages.vue")['default']>
export const LazyPageBuyHouseBasicPriceInfo: LazyComponent<typeof import("../pages/buy/_components/house/basic/PriceInfo.vue")['default']>
export const LazyPageBuyHouseInformationBasic: LazyComponent<typeof import("../pages/buy/_components/house/information/Basic.vue")['default']>
export const LazyPageBuyHouseInformationFunction: LazyComponent<typeof import("../pages/buy/_components/house/information/Function.vue")['default']>
export const LazyPageBuyHouseInformationOther: LazyComponent<typeof import("../pages/buy/_components/house/information/Other.vue")['default']>
export const LazyPageBuyHouseInformationParking: LazyComponent<typeof import("../pages/buy/_components/house/information/Parking.vue")['default']>
export const LazyPageBuyHouseInformationPin: LazyComponent<typeof import("../pages/buy/_components/house/information/Pin.vue")['default']>
export const LazyPageBuyHouseInformationPrice: LazyComponent<typeof import("../pages/buy/_components/house/information/Price.vue")['default']>
export const LazyPageBuyHouseInformationContainer: LazyComponent<typeof import("../pages/buy/_components/house/information/_Container.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyErrorMessage: LazyComponent<typeof import("vee-validate")['ErrorMessage']>
export const LazyField: LazyComponent<typeof import("vee-validate")['Field']>
export const LazyFieldArray: LazyComponent<typeof import("vee-validate")['FieldArray']>
export const LazyForm: LazyComponent<typeof import("vee-validate")['Form']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
