// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/2/27 上午8:14:06
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["F:/Git/YungChing/Dev/HouseFun/Backstage/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Backstage/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Backstage/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Backstage/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Backstage/plugins/**/*.{js,ts,mjs}","F:/Git/YungChing/Dev/HouseFun/Backstage/composables/**/*.{js,ts,mjs}","F:/Git/YungChing/Dev/HouseFun/Backstage/utils/**/*.{js,ts,mjs}","F:/Git/YungChing/Dev/HouseFun/Backstage/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Backstage/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Backstage/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Backstage/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;