// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/4/21 下午1:44:53
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["F:/Git/YungChing/Dev/HouseFun/Official/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Official/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Official/containers/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Official/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Official/plugins/**/*.{js,ts,mjs}","F:/Git/YungChing/Dev/HouseFun/Official/composables/**/*.{js,ts,mjs}","F:/Git/YungChing/Dev/HouseFun/Official/utils/**/*.{js,ts,mjs}","F:/Git/YungChing/Dev/HouseFun/Official/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Official/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Official/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","F:/Git/YungChing/Dev/HouseFun/Official/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;