import { defineStore } from 'pinia'

export const useBuyBasicStore = defineStore('buyBasic', () => {
  const components = shallowReadonly([
    {
      id: 'CardFilterInfo',
      label: '基本資料',
    },
    {
      id: 'CardFilterPrice',
      label: '價格資訊',
    },
    {
      id: 'CardFilterPing',
      label: '坪數資訊',
    },
    {
      id: 'CardFilterManage',
      label: '管理資訊',
    },
    {
      id: 'CardFilterParking',
      label: '車位資訊',
    },
    {
      id: 'CardFilterFeature',
      label: '特色描述',
    },
    {
      id: 'CardFilterPictures',
      label: '照片資訊',
    },
    {
      id: 'CardFilterMedia',
      label: '影音設定',
    },
    {
      id: 'CardFilterPosterInfo',
      label: '聯絡資訊',
    },
    {
      id: 'CardFilterTerms',
      label: '使用條款',
    },
  ])
  const apiData = ref({
    caseInfo: {
      casePostStatus: 0,
      hid: 0,
      caseID: '',
      hfID: 0,
      caseNo: null,
      casePurposeToken: null,
      caseTitle: null,
      cityID: null,
      districtID: null,
      road: null,
      lane: null,
      alley: null,
      addrNum: null,
      addrNumOf: null,
      floor: null,
      addrNumOfFloor: null,
      caseTypeToken: null,
      caseUsageToken: null,
      caseZoingToken: 1,
      caseZoingTypeToken: null,
      caseZoingTypeOther: null,
      caseAgeIdentifyToken: 1,
      caseLandNo: null,
      isSingleFloor: true,
      floorFromToken: 1,
      caseFloorFrom: null,
      floorToToken: 1,
      caseFloorTo: null,
      caseFloorTotal: null,
      caseAge: null,
      caseCompletedYear: null,
      caseCompletedMonth: null,
      isCaseUnknownAge: false,
      isCasePreSale: false,
      isCaseCommunity: false,
      caseCommunityID: null,
      caseCommunityName: null,
      caseRoom: null,
      caseLivingRoom: null,
      caseBathroom: null,
      caseBalcony: null,
      isCaseOpenConcept: false,
      isCaseAddtion: false,
      caseAddRoom: null,
      caseAddLivingRoom: null,
      caseAddBathroom: null,
      caseAddBalcony: null,
      isCaseHasElevator: true,
      caseElevatorCount: null,
      caseFaceToken: null,
      caseStructureToken: null,
      caseBarrierfreeToken: null,
      casePrice: null,
      isCasePriceIncludeParking: false,
      caseParkingPrice: null,
      isCasePriceUnitAuto: true,
      casePriceUnit: null,
      isCasePricePerPinDeductParking: false,
      isCaseSqUnitPin: true,
      caseBuildSqPin: null,
      caseBuildSqM: null,
      isCaseBuildSqIncludeParking: false,
      caseParkingSqPin: null,
      caseParkingSqM: null,
      caseMainSqPin: null,
      caseMainSqM: null,
      caseAffiliatedSqPin: null,
      caseAffiliatedSqM: null,
      isCaseAttachedSqAutoCalculate: false,
      caseBalconySqPin: null,
      caseBalconySqM: null,
      casePlatformSqPin: null,
      casePlatformSqM: null,
      caseTerraceSqPin: null,
      caseTerraceSqM: null,
      caseStairwellSqPin: null,
      caseStairwellSqM: null,
      caseMezzanineSqPin: null,
      caseMezzanineSqM: null,
      caseBasementSqPin: null,
      caseBasementSqM: null,
      caseOtherSqPin: null,
      caseOtherSqM: null,
      caseAmenitieSqPin: null,
      caseAmenitieSqM: null,
      caseAmenitieSqRqtio: null,
      isCaseAmenitieSqRqtioAuto: true,
      caseLandSqPin: null,
      caseLandSqM: null,
      caseManageTypeToken: null,
      caseManageDutyToken: null,
      caseManageFeePeriodToken: null,
      caseManageFee: null,
      isCaseParking: true,
      parkingInfos: [],
      caseDescription: null,
      caseFeatureToken: null,
      caseFeatureCustomize: null,
      casePictures: [],
      caseLayout: null,
      caseVideoDisplayToken: 1,
      caseVideoTypeToken: null,
      caseVideoUrl: null,
      caseFloorplanUrl: null,
      posterDataSourceToken: 1,
      posterInfo: {
        agentID: null,
        agentName: null,
        isShowNickname: false,
        agentPhone: null,
        isAgentDND: false,
        agentLine: null,
      },
      isAgreeUserTerm: false,
    },
    imgCases: [],
    imgFloorplan: null,
  })
  const options = readonly({
    unit: [
      {
        id: 'pin',
        label: '坪',
        value: true,
        convert: 3.30579, // 1 坪 = 3.30579 平方公尺,
        toFixed: 2,
      },
      {
        id: 'sqMeters',
        label: '平方公尺',
        value: false,
        convert: 0.3025, // 1 平方公尺 = 0.3025 坪
        toFixed: 2,
      },
    ],
  })
  const address = ref(null)
  const pingData = ref({
    caseBuildSq: null,
    caseParkingSq: null,
    caseMainSq: null,
    caseAffiliatedSq: null,
    caseBalconySq: null,
    casePlatformSq: null,
    caseTerraceSq: null,
    caseStairwellSq: null,
    caseMezzanineSq: null,
    caseBasementSq: null,
    caseOtherSq: null,
    caseAmenitieSq: null,
    caseLandSq: null,
  })
  const pictures = shallowReadonly({
    maxSizeMB: 25,
    maxCount: 25,
  })

  return {
    components,
    apiData,
    options,
    address,
    pingData,
    pictures,
  }
})
