import { defineStore } from 'pinia'

export const useBuyProjectStore = defineStore('buyProject', () => {
  const NAME = '好房網買屋 Housefun 管理後台'
  const options = ref({
    casePurpose: null,
    city: null,
    area: null,
    caseType: null,
    caseUsage: null,
    caseZoing: null,
    zoingCity: null,
    zoingLand: null,
    floor: null,
    face: null,
    structure: null,
    barrierFree: null,
    manageType: null,
    manageDuty: null,
    managePay: null,
    videoType: null,
    feature: null,
  })
  const apiData = ref({
    casePurposeToken: '',
    caseTitle: '',
    cityID: '',
    districtID: '',
    road: '',
    lane: '',
    alley: '',
    addrNum: '',
    addrNumOf: '',
    floor: '',
    addrNumOfFloor: '',
    caseTypeToken: '',
    caseUsageToken: '',
    caseZoingToken: '',
    caseZoingTypeToken: '',
    caseZoingTypeOther: '',
    caseLandNo: '',
    isSingleFloor: true,
    floorFromToken: '',
    caseFloorFrom: '',
    floorToToken: '',
    caseFloorTo: '',
    caseFloorTotal: '',
    caseAge: '',
    caseCompletedYear: '',
    caseCompletedMonth: '',
    isCaseUnknownAge: false,
    isCasePreSale: false,
    isCaseCommunity: false,
    caseCommunityID: '',
    caseCommunityName: '',
    caseRoom: '',
    caseLivingRoom: '',
    caseBathroom: '',
    caseBalcony: '',
    isCaseOpenConcept: false,
    isCaseAddtion: false,
    caseAddRoom: '',
    caseAddLivingRoom: '',
    caseAddBathroom: '',
    caseAddBalcony: '',
    isCaseHasElevator: true,
    caseElevatorCount: '',
    caseFaceToken: '',
    caseStructureToken: '',
    caseBarrierfreeToken: '',
    casePrice: '',
    isCasePriceIncludeParking: false,
    caseParkingPrice: '',
    casePriceUnit: '',
    isCasePricePerPinDeductParking: false,
    caseBuildSqPin: '',
    caseBuildSqM: '',
    isCaseBuildSqIncludeParking: false,
    caseParkingSqPin: '',
    caseParkingSqM: '',
    caseMainSqPin: '',
    caseMainSqM: '',
    caseAffiliatedSqPin: '',
    caseAffiliatedSqM: '',
    isCaseAttachedSqAutoCalculate: false,
    caseBalconySqPin: '',
    caseBalconySqM: '',
    casePlatformSqPin: '',
    casePlatformSqM: '',
    caseTerraceSqPin: '',
    caseTerraceSqM: '',
    caseStairwellSqPin: '',
    caseStairwellSqM: '',
    caseMezzanineSqPin: '',
    caseMezzanineSqM: '',
    caseBasementSqPin: '',
    caseBasementSqM: '',
    caseOtherSqPin: '',
    caseOtherSqM: '',
    caseAmenitieSqPin: '',
    caseAmenitieSqM: '',
    caseLandSqPin: '',
    caseLandSqM: '',
    caseManageTypeToken: '',
    caseManageDutyToken: '',
    caseManageFeePeriodToken: '',
    caseManageFee: '',
    caseDescription: '',
    caseFeatureToken: '',
    listCasePicUrl: [],
    caseVideoTypeToken: '',
    caseVideoUrl: '',
    caseFloorplanUrl: '',
    posterInfo: {
      agentID: '',
      agentName: '',
      isShowNickname: false,
      agentPhone: '',
      isAgentDND: false,
      agentLine: '',
    },
  })

  return {
    NAME,
    options,
    apiData,
  }
})
