import { defineStore } from 'pinia'

export const useBuyProjectStore = defineStore('buyProject', () => {
  const NAME = '好房網買屋 Housefun 管理後台'
  const options = ref({
    casePurpose: null,
    city: null,
    area: null,
    caseType: null,
    caseUsage: null,
    caseZoing: null,
    zoingCity: null,
    zoingLand: null,
    ageIdentify: null,
    floor: null,
    face: null,
    structure: null,
    barrierFree: null,
    manageType: null,
    manageDuty: null,
    managePay: null,
    parkingMode: null,
    parkingType: null,
    parkingReg: null,
    parkingPayPeriod: null,
    videoDisplay: null,
    videoType: null,
    feature: null,
    posterDataSource: null,
  })
  const apiData = ref({
    casePostStatus: 0,
    hid: 0,
    caseID: null,
    hfID: 0,
    caseNo: null,
    casePurposeToken: null,
    caseTitle: null,
    cityID: null,
    districtID: null,
    road: null,
    lane: null,
    alley: null,
    addrNum: null,
    addrNumOf: null,
    floor: null,
    addrNumOfFloor: null,
    caseTypeToken: null,
    caseUsageToken: null,
    caseZoingToken: null,
    caseZoingTypeToken: null,
    caseZoingTypeOther: null,
    caseAgeIdentifyToken: 0,
    caseLandNo: null,
    isSingleFloor: true,
    floorFromToken: 0,
    caseFloorFrom: null,
    floorToToken: 0,
    caseFloorTo: null,
    caseFloorTotal: null,
    caseAge: null,
    caseCompletedYear: null,
    caseCompletedMonth: null,
    isCaseUnknownAge: false,
    isCasePreSale: false,
    isCaseCommunity: false,
    caseCommunityID: null,
    caseCommunityName: null,
    caseRoom: null,
    caseLivingRoom: null,
    caseBathroom: null,
    caseBalcony: null,
    isCaseOpenConcept: false,
    isCaseAddtion: false,
    caseAddRoom: null,
    caseAddLivingRoom: null,
    caseAddBathroom: null,
    caseAddBalcony: null,
    isCaseHasElevator: true,
    caseElevatorCount: null,
    caseFaceToken: null,
    caseStructureToken: null,
    caseBarrierfreeToken: null,
    casePrice: null,
    isCasePriceIncludeParking: false,
    caseParkingPrice: null,
    isCasePriceUnitAuto: true,
    casePriceUnit: null,
    isCasePricePerPinDeductParking: false,
    isCaseSqUnitPin: true,
    caseBuildSqPin: null,
    caseBuildSqM: null,
    isCaseBuildSqIncludeParking: false,
    caseParkingSqPin: null,
    caseParkingSqM: null,
    caseMainSqPin: null,
    caseMainSqM: null,
    caseAffiliatedSqPin: null,
    caseAffiliatedSqM: null,
    isCaseAttachedSqAutoCalculate: false,
    caseBalconySqPin: null,
    caseBalconySqM: null,
    casePlatformSqPin: null,
    casePlatformSqM: null,
    caseTerraceSqPin: null,
    caseTerraceSqM: null,
    caseStairwellSqPin: null,
    caseStairwellSqM: null,
    caseMezzanineSqPin: null,
    caseMezzanineSqM: null,
    caseBasementSqPin: null,
    caseBasementSqM: null,
    caseOtherSqPin: null,
    caseOtherSqM: null,
    caseAmenitieSqPin: null,
    caseAmenitieSqM: null,
    caseAmenitieSqRqtio: null,
    isCaseAmenitieSqRqtioAuto: true,
    caseLandSqPin: null,
    caseLandSqM: null,
    caseManageTypeToken: null,
    caseManageDutyToken: null,
    caseManageFeePeriodToken: null,
    caseManageFee: null,
    isCaseParking: true,
    parkingInfos: [],
    caseDescription: null,
    caseFeatureToken: null,
    listCasePicUrl: [],
    caseVideoDisplayToken: null,
    caseVideoTypeToken: null,
    caseVideoUrl: null,
    caseFloorplanUrl: null,
    posterDataSourceToken: null,
    posterInfo: {
      agentID: null,
      agentName: null,
      isShowNickname: false,
      agentPhone: null,
      isAgentDND: false,
      agentLine: null,
    },
    isAgreeUserTerm: false,
  })
  const parkingInfo = readonly({
    parkingID: '',
    caseParkingModeToken: '',
    caseParkingCount: '',
    caseParkingTypeToken: '',
    caseParkingRegToken: '',
    caseParkingFeePayTypeToken: '',
    caseParkingFee: '',
    isCaseParkingFeeInclude: true,
  })

  return {
    NAME,
    options,
    apiData,
    parkingInfo,
  }
})
